# Example repo config for worktree-new / worktree-remove.
#
# Setup:
#   1. Copy this file into the target repository as scripts/local/worktree-config.sh
#      cp ~/.local/share/worktree/config.example.sh <repo>/scripts/local/worktree-config.sh
#   2. To keep it out of git, add scripts/local/ to .git/info/exclude
#   3. Adjust the variables and functions to match the repository
#
# Contract with the engine:
#   - This file is sourced by the engine (bash), so it must be valid bash
#   - Required variable:  MAX_SLOT
#   - Required function:  setup_worktree (called by worktree-new after gwq add)
#   - Optional function:  cleanup_before_remove (called by worktree-remove
#                         before gwq remove)
#   - Variables provided by the engine:
#       $SLOT       slot number (1..MAX_SLOT; not provided on remove)
#       $WT         absolute path of the worktree
#       $BRANCH     branch name
#       $REPO_ROOT  root of the main repository
#   - Hooks run in the same process as the engine. If a hook needs to cd,
#     wrap it in a subshell ( ) so the engine's working directory is untouched
#   - Slot bookkeeping is engine-owned (.git/worktrees/<name>/slot); the config
#     does not need to record the slot anywhere for the engine's sake
#
# Everything below the contract is repo-internal convention. The sample assumes
# a "Rails + docker compose + shared test MySQL" setup; replace "myapp" with
# your actual project name, or rewrite the helpers entirely for other stacks.

MAX_SLOT=3             # fixed number of slots (test DBs _wt1.._wtN are reused)
PROJECT_PREFIX=myapp   # repo-internal: compose project name, volume names, etc.

# Required hook: provision the worktree so tests can run in it
setup_worktree() {
  echo "==> copying ignored files"
  copy_ignored_files
  echo "==> generating compose.override.yaml"
  generate_override
  echo "==> preparing gems"
  prepare_gems
  echo "==> preparing test DB (slot wt${SLOT})"
  prepare_test_db
  echo "    run specs: cd $WT && docker compose run --rm web bundle exec rspec spec/..."
}

# Optional hook: called by worktree-remove before gwq remove
# Test DBs and the shared gem volume are kept for slot reuse
cleanup_before_remove() {
  (
    cd "$WT"
    docker compose down --remove-orphans
  )
}

# --- Private helpers below (not part of the engine contract) ---

# Copy ignored files that a fresh worktree does not inherit from main
copy_ignored_files() {
  # e.g. schema (needed as the schema-load source when it is ignored and
  # migrations are the source of truth)
  cp "$REPO_ROOT/db/schema.rb" "$WT/db/schema.rb"
  # e.g. Claude Code permission settings
  mkdir -p "$WT/.claude"
  cp "$REPO_ROOT/.claude/settings.local.json" "$WT/.claude/settings.local.json"
}

# Generate the worktree's compose.override.yaml from scratch
generate_override() {
  cat > "$WT/compose.override.yaml" <<EOF
# Generated by worktree-new for slot wt${SLOT}. Not the same file as main's override.
name: ${PROJECT_PREFIX}-wt${SLOT}

services:
  web:
    image: ${PROJECT_PREFIX}-web          # reuse the image already built by main
    ports: !override []                   # an accidental up cannot collide on ports
    environment:
      TEST_ENV_NUMBER: _wt${SLOT}         # logical separation key for the test DB

volumes:
  # Swap the base bundler-volume for an external volume shared across worktrees
  bundler-volume:
    external: true
    name: ${PROJECT_PREFIX}_wt_bundle
  # Share main's packs / assets (for bundle resolution in the view layer)
  public-packs-volume:
    external: true
    name: ${PROJECT_PREFIX}_public-packs-volume
  public-assets-volume:
    external: true
    name: ${PROJECT_PREFIX}_public-assets-volume
EOF
}

# Prepare gems (a few seconds no-op when already satisfied)
prepare_gems() {
  # Shared volume (an empty volume is auto-seeded from the image's vendor/bundle
  # on first mount)
  docker volume create "${PROJECT_PREFIX}_wt_bundle" >/dev/null
  # flock guards against concurrent installs into the shared volume
  (
    cd "$WT"
    docker compose run --rm web flock vendor/bundle/.bundle-install.lock bundle install
  )
}

# Prepare the test DB (suffix: _wt${SLOT})
# Note: RAILS_ENV switches credentials and thus the DB name, so every command
#       must carry RAILS_ENV=test
prepare_test_db() {
  (
    cd "$WT"
    docker compose run --rm web bash -c \
      "RAILS_ENV=test bin/rails db:test:prepare && RAILS_ENV=test bin/rails db:migrate && RAILS_ENV=test bin/rails db:seed"
  )
}
