# ~/.config/yazi/yazi.toml

[mgr]
sort_by = "natural"
sort_dir_first = true
show_hidden = true
show_symlink = true
scrolloff = 5
title_format = "Yazi: {cwd}"

[preview]
wrap = "no"
tab_size = 2
max_width = 600
max_height = 900

[opener]
edit = [
	{ run = "$EDITOR %s", block = true, for = "unix" },
]
open = [
	{ run = "open %s", desc = "Open", for = "macos" },
]
