model = "gpt-5.3-codex"
personality = "pragmatic"
model_reasoning_effort = "high"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[mcp_servers.awslabs-aws-documentation-mcp-server]
command = "uvx"
args = ["awslabs.aws-documentation-mcp-server@latest"]

[mcp_servers.awslabs-aws-documentation-mcp-server.env]
FASTMCP_LOG_LEVEL = "ERROR"

[mcp_servers.chrome-devtools-mcp]
command = "chrome-devtools-mcp"
args = ["--headless=true", "--isolated=true"]

[mcp_servers.playwright-mcp]
command = "playwright-mcp"
args = ["--headless"]

[mcp_servers.rails-mcp-server]
command = "rails-mcp-server"

[mcp_servers.serena]
command = "uvx"
args = ["--from", "git+https://github.com/oraios/serena", "serena", "start-mcp-server", "--enable-web-dashboard", "false"]
